### ISSUE TITLE
DQN.py:79:

### ISSUE THREAD

**Issue by OzgunKB** [maurock/snake-ga#3]
E:\NGBH\Reinforcement Learning\snake-ga-master\DQN.py:79: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=120)`
  model.add(Dense(output_dim=120, activation='relu', input_dim=11))
WARNING:tensorflow:From C:\python64\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\python64\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
E:\NGBH\Reinforcement Learning\snake-ga-master\DQN.py:81: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=120)`
  model.add(Dense(output_dim=120, activation='relu'))
E:\NGBH\Reinforcement Learning\snake-ga-master\DQN.py:83: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=120)`
  model.add(Dense(output_dim=120, activation='relu'))
E:\NGBH\Reinforcement Learning\snake-ga-master\DQN.py:85: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=3)`
  model.add(Dense(output_dim=3, activation='softmax'))
Traceback (most recent call last):
  File "E:\NGBH\Reinforcement Learning\snake-ga-master\snakeClass.py", line 231, in <module>
    run()
  File "E:\NGBH\Reinforcement Learning\snake-ga-master\snakeClass.py", line 181, in run
    game = Game(440, 440)
  File "E:\NGBH\Reinforcement Learning\snake-ga-master\snakeClass.py", line 23, in __init__
    self.bg = pygame.image.load("img/background.png")
pygame.error: Couldn't open img/background.png
![ss](https://user-images.githubusercontent.com/48881141/63636093-3983fa00-c673-11e9-91f5-056482ecafa5.JPG)

**Comment by chankruze** [comment]
It can't find the background image. Make sure your directory is correct if not or if using virtual environment, change the path relatively to the image.
